// Available vehicle types
export const vehicleTypes = [
  { value: 'Sedan', label: 'Sedan' },
  { value: 'SUV', label: 'SUV' },
  { value: 'Truck', label: 'Truck' },
  { value: 'Van', label: 'Van' },
  { value: 'Hatchback', label: 'Hatchback' },
  { value: 'Convertible', label: 'Convertible' },
  { value: 'Coupe', label: 'Coupe' },
  { value: 'Wagon', label: 'Wagon' },
  { value: 'Minivan', label: 'Minivan' },
  { value: 'Crossover', label: 'Crossover' },
];

// Available car makes
export const carMakes = [
  { value: 'Acura', label: 'Acura' },
  { value: 'Alfa Romeo', label: 'Alfa Romeo' },
  { value: 'Aston Martin', label: 'Aston Martin' },
  { value: 'Audi', label: 'Audi' },
  { value: 'Bentley', label: 'Bentley' },
  { value: 'BMW', label: 'BMW' },
  { value: 'Buick', label: 'Buick' },
  { value: 'Cadillac', label: 'Cadillac' },
  { value: 'Chevrolet', label: 'Chevrolet' },
  { value: 'Chrysler', label: 'Chrysler' },
  { value: 'Dodge', label: 'Dodge' },
  { value: 'Ferrari', label: 'Ferrari' },
  { value: 'Fiat', label: 'Fiat' },
  { value: 'Ford', label: 'Ford' },
  { value: 'Genesis', label: 'Genesis' },
  { value: 'GMC', label: 'GMC' },
  { value: 'Honda', label: 'Honda' },
  { value: 'Hyundai', label: 'Hyundai' },
  { value: 'Infiniti', label: 'Infiniti' },
  { value: 'Jaguar', label: 'Jaguar' },
  { value: 'Jeep', label: 'Jeep' },
  { value: 'Kia', label: 'Kia' },
  { value: 'Lamborghini', label: 'Lamborghini' },
  { value: 'Land Rover', label: 'Land Rover' },
  { value: 'Lexus', label: 'Lexus' },
  { value: 'Lincoln', label: 'Lincoln' },
  { value: 'Lotus', label: 'Lotus' },
  { value: 'Maserati', label: 'Maserati' },
  { value: 'Mazda', label: 'Mazda' },
  { value: 'McLaren', label: 'McLaren' },
  { value: 'Mercedes-Benz', label: 'Mercedes-Benz' },
  { value: 'Mini', label: 'Mini' },
  { value: 'Mitsubishi', label: 'Mitsubishi' },
  { value: 'Nissan', label: 'Nissan' },
  { value: 'Porsche', label: 'Porsche' },
  { value: 'Ram', label: 'Ram' },
  { value: 'Rolls-Royce', label: 'Rolls-Royce' },
  { value: 'Subaru', label: 'Subaru' },
  { value: 'Tesla', label: 'Tesla' },
  { value: 'Toyota', label: 'Toyota' },
  { value: 'Volkswagen', label: 'Volkswagen' },
  { value: 'Volvo', label: 'Volvo' },
];

// Car model data by make
export const carModelsByMake: Record<string, Array<{value: string, label: string}>> = {
  'Acura': [
    { value: 'ILX', label: 'ILX' },
    { value: 'MDX', label: 'MDX' },
    { value: 'RDX', label: 'RDX' },
    { value: 'TLX', label: 'TLX' },
    { value: 'NSX', label: 'NSX' },
  ],
  'Audi': [
    { value: 'A3', label: 'A3' },
    { value: 'A4', label: 'A4' },
    { value: 'A5', label: 'A5' },
    { value: 'A6', label: 'A6' },
    { value: 'A7', label: 'A7' },
    { value: 'A8', label: 'A8' },
    { value: 'Q3', label: 'Q3' },
    { value: 'Q5', label: 'Q5' },
    { value: 'Q7', label: 'Q7' },
    { value: 'Q8', label: 'Q8' },
    { value: 'e-tron', label: 'e-tron' },
  ],
  'BMW': [
    { value: '2 Series', label: '2 Series' },
    { value: '3 Series', label: '3 Series' },
    { value: '4 Series', label: '4 Series' },
    { value: '5 Series', label: '5 Series' },
    { value: '7 Series', label: '7 Series' },
    { value: '8 Series', label: '8 Series' },
    { value: 'X1', label: 'X1' },
    { value: 'X3', label: 'X3' },
    { value: 'X5', label: 'X5' },
    { value: 'X7', label: 'X7' },
    { value: 'i3', label: 'i3' },
    { value: 'i8', label: 'i8' },
  ],
  'Chevrolet': [
    { value: 'Bolt', label: 'Bolt' },
    { value: 'Camaro', label: 'Camaro' },
    { value: 'Corvette', label: 'Corvette' },
    { value: 'Equinox', label: 'Equinox' },
    { value: 'Malibu', label: 'Malibu' },
    { value: 'Silverado', label: 'Silverado' },
    { value: 'Suburban', label: 'Suburban' },
    { value: 'Tahoe', label: 'Tahoe' },
    { value: 'Traverse', label: 'Traverse' },
    { value: 'Trax', label: 'Trax' },
  ],
  'Ford': [
    { value: 'Bronco', label: 'Bronco' },
    { value: 'EcoSport', label: 'EcoSport' },
    { value: 'Edge', label: 'Edge' },
    { value: 'Escape', label: 'Escape' },
    { value: 'Explorer', label: 'Explorer' },
    { value: 'F-150', label: 'F-150' },
    { value: 'Mustang', label: 'Mustang' },
    { value: 'Ranger', label: 'Ranger' },
    { value: 'Transit', label: 'Transit' },
    { value: 'Mustang Mach-E', label: 'Mustang Mach-E' },
  ],
  'Honda': [
    { value: 'Accord', label: 'Accord' },
    { value: 'Civic', label: 'Civic' },
    { value: 'CR-V', label: 'CR-V' },
    { value: 'Fit', label: 'Fit' },
    { value: 'HR-V', label: 'HR-V' },
    { value: 'Insight', label: 'Insight' },
    { value: 'Odyssey', label: 'Odyssey' },
    { value: 'Passport', label: 'Passport' },
    { value: 'Pilot', label: 'Pilot' },
    { value: 'Ridgeline', label: 'Ridgeline' },
  ],
  'Hyundai': [
    { value: 'Accent', label: 'Accent' },
    { value: 'Elantra', label: 'Elantra' },
    { value: 'Ioniq', label: 'Ioniq' },
    { value: 'Kona', label: 'Kona' },
    { value: 'Palisade', label: 'Palisade' },
    { value: 'Santa Fe', label: 'Santa Fe' },
    { value: 'Sonata', label: 'Sonata' },
    { value: 'Tucson', label: 'Tucson' },
    { value: 'Veloster', label: 'Veloster' },
    { value: 'Venue', label: 'Venue' },
  ],
  'Kia': [
    { value: 'Forte', label: 'Forte' },
    { value: 'K5', label: 'K5' },
    { value: 'Niro', label: 'Niro' },
    { value: 'Optima', label: 'Optima' },
    { value: 'Rio', label: 'Rio' },
    { value: 'Sedona', label: 'Sedona' },
    { value: 'Seltos', label: 'Seltos' },
    { value: 'Sorento', label: 'Sorento' },
    { value: 'Soul', label: 'Soul' },
    { value: 'Sportage', label: 'Sportage' },
    { value: 'Stinger', label: 'Stinger' },
    { value: 'Telluride', label: 'Telluride' },
  ],
  'Lexus': [
    { value: 'ES', label: 'ES' },
    { value: 'GS', label: 'GS' },
    { value: 'GX', label: 'GX' },
    { value: 'IS', label: 'IS' },
    { value: 'LC', label: 'LC' },
    { value: 'LS', label: 'LS' },
    { value: 'LX', label: 'LX' },
    { value: 'NX', label: 'NX' },
    { value: 'RC', label: 'RC' },
    { value: 'RX', label: 'RX' },
    { value: 'UX', label: 'UX' },
  ],
  'Mercedes-Benz': [
    { value: 'A-Class', label: 'A-Class' },
    { value: 'C-Class', label: 'C-Class' },
    { value: 'CLA', label: 'CLA' },
    { value: 'CLS', label: 'CLS' },
    { value: 'E-Class', label: 'E-Class' },
    { value: 'G-Class', label: 'G-Class' },
    { value: 'GLA', label: 'GLA' },
    { value: 'GLC', label: 'GLC' },
    { value: 'GLE', label: 'GLE' },
    { value: 'GLS', label: 'GLS' },
    { value: 'S-Class', label: 'S-Class' },
  ],
  'Nissan': [
    { value: 'Altima', label: 'Altima' },
    { value: 'Armada', label: 'Armada' },
    { value: 'Frontier', label: 'Frontier' },
    { value: 'GT-R', label: 'GT-R' },
    { value: 'Kicks', label: 'Kicks' },
    { value: 'Leaf', label: 'Leaf' },
    { value: 'Maxima', label: 'Maxima' },
    { value: 'Murano', label: 'Murano' },
    { value: 'Pathfinder', label: 'Pathfinder' },
    { value: 'Rogue', label: 'Rogue' },
    { value: 'Sentra', label: 'Sentra' },
    { value: 'Titan', label: 'Titan' },
    { value: 'Versa', label: 'Versa' },
  ],
  'Subaru': [
    { value: 'Ascent', label: 'Ascent' },
    { value: 'BRZ', label: 'BRZ' },
    { value: 'Crosstrek', label: 'Crosstrek' },
    { value: 'Forester', label: 'Forester' },
    { value: 'Impreza', label: 'Impreza' },
    { value: 'Legacy', label: 'Legacy' },
    { value: 'Outback', label: 'Outback' },
    { value: 'WRX', label: 'WRX' },
  ],
  'Tesla': [
    { value: 'Model 3', label: 'Model 3' },
    { value: 'Model S', label: 'Model S' },
    { value: 'Model X', label: 'Model X' },
    { value: 'Model Y', label: 'Model Y' },
    { value: 'Cybertruck', label: 'Cybertruck' },
    { value: 'Roadster', label: 'Roadster' },
  ],
  'Toyota': [
    { value: '4Runner', label: '4Runner' },
    { value: '86', label: '86' },
    { value: 'Avalon', label: 'Avalon' },
    { value: 'Camry', label: 'Camry' },
    { value: 'Corolla', label: 'Corolla' },
    { value: 'Highlander', label: 'Highlander' },
    { value: 'Prius', label: 'Prius' },
    { value: 'RAV4', label: 'RAV4' },
    { value: 'Sequoia', label: 'Sequoia' },
    { value: 'Sienna', label: 'Sienna' },
    { value: 'Tacoma', label: 'Tacoma' },
    { value: 'Tundra', label: 'Tundra' },
    { value: 'Venza', label: 'Venza' },
    { value: 'Supra', label: 'Supra' },
  ],
  'Volkswagen': [
    { value: 'Arteon', label: 'Arteon' },
    { value: 'Atlas', label: 'Atlas' },
    { value: 'Golf', label: 'Golf' },
    { value: 'ID.4', label: 'ID.4' },
    { value: 'Jetta', label: 'Jetta' },
    { value: 'Passat', label: 'Passat' },
    { value: 'Taos', label: 'Taos' },
    { value: 'Tiguan', label: 'Tiguan' },
  ],
};

// Default models for makes not explicitly defined
export const defaultModels = [
  { value: 'Standard', label: 'Standard' },
  { value: 'Deluxe', label: 'Deluxe' },
  { value: 'Premium', label: 'Premium' },
  { value: 'Sport', label: 'Sport' },
  { value: 'Limited', label: 'Limited' },
];

// Generate year options from 1990 to current year + 1
export const yearOptions = (() => {
  const currentYear = new Date().getFullYear();
  const years = [];
  for (let year = currentYear + 1; year >= 1990; year--) {
    years.push({ value: year.toString(), label: year.toString() });
  }
  return years;
})();

// Common car colors
export const carColors = [
  { value: 'Black', label: 'Black' },
  { value: 'White', label: 'White' },
  { value: 'Silver', label: 'Silver' },
  { value: 'Gray', label: 'Gray' },
  { value: 'Red', label: 'Red' },
  { value: 'Blue', label: 'Blue' },
  { value: 'Green', label: 'Green' },
  { value: 'Yellow', label: 'Yellow' },
  { value: 'Orange', label: 'Orange' },
  { value: 'Brown', label: 'Brown' },
  { value: 'Gold', label: 'Gold' },
  { value: 'Beige', label: 'Beige' },
  { value: 'Purple', label: 'Purple' },
  { value: 'Pink', label: 'Pink' },
  { value: 'Burgundy', label: 'Burgundy' },
];